name: CI Pipeline
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  Lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up Node Js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint
  test:
    name: Test on node ${{ matrix.node-version }}
    needs: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false #Don't cancel other matrix jobs if one fails
      matrix:
        node-version: [18, 20, 22]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up Node Js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Upload coverage report
        if: always() # Upload even if tests fail
        uses: actions/upload-artifact@v6
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage/
          retention-days: 5
  build:
    name: Build and Publish ${{ matrix.node-version }}
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false #Don't cancel other matrix jobs if one fails
      matrix:
        node-version: [18, 20, 22]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up Node Js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
